// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNdo89sseBotBPUNX3_h96gXL5mNWPfc',
    appId: '1:685087075498:web:5bf55da39b20c79be7f4d3',
    messagingSenderId: '685087075498',
    projectId: 'pbchat-app',
    authDomain: 'pbchat-app.firebaseapp.com',
    storageBucket: 'pbchat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu8r6rKl7VAV6bt2luLyoK-2eWbvMlVyw',
    appId: '1:685087075498:android:3af6e5b1e9533bfce7f4d3',
    messagingSenderId: '685087075498',
    projectId: 'pbchat-app',
    storageBucket: 'pbchat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACiTYhJzWCTWDRT5lRoY7mL2ultJY1ds0',
    appId: '1:685087075498:ios:8ceeb0f44e0e8ea1e7f4d3',
    messagingSenderId: '685087075498',
    projectId: 'pbchat-app',
    storageBucket: 'pbchat-app.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
